version: "3.9"

services:
  dashboard:
    build: .
    container_name: dashboard_app
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: unless-stopped